version: '3.0'

services:
  user-postgres:
    image: postgres:14-alpine
    container_name: galleryDB
    restart: always
    ports:
      - "5051:5051"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=sarah
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=galleryDB
    build: .