version: '3.0'

services:
  user-postgres:
    image: postgres:14-alpine
    container_name: usersDB
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=sarah
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=artful
    build: .